server:
  servlet:
    context-path: /web
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 12345678
      #B接池配置
      initial-size: 5
      min-idle: 20
      #接等待超r
      max-wait: 30000
      #配置z查可以P]的空eg隔rg
      time-between-eviction-runs-millis: 60000
      #配置B接池在池中的最小生存rg
      min-evictable-idle-time-millis: 30000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打_PSCache，并且指定每接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      #配置O控yr截的filters，去掉后O控界面sqlo法y，‘wall’用於防火
      filter:
        stat:
          log-slow-sql: true
      #springO控aop切入c，如x.y.z.service.*,配置多英文逗分割

#      #webStaFilter配置
#      web-stat-filter:
#        enabled: true
#        #添加^Vt
#        url-pattern: /*
#        #忽略^V的格式
#        exclusions: '*.js,*.gif,*.jgp,*.png,*.css,*.ico,/druid/*'
#          # StatViewServlet配置
#          stat-view-servlet:
#           enabled: true
#            # 访问路径为/druid时，跳转到StatViewServlet
#            url-pattern: /druid/*
#            # 是否能够重置数据
#            reset-enable: false
#            # 需要账号密码才能访问控制台
#            login-username: druid
#            login-password: druid123
#            # IP白名单
#            # allow: 127.0.0.1
#            #　IP黑名单（共同存在时，deny优先于allow）
#            # deny: 192.168.1.218
#
#          # 配置StatFilter
#          filter:
#            stat:
#             log-slow-sql: true
